apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: selim2002/tpfoyer:latest
          imagePullPolicy: Never   # <-- important pour utiliser l'image locale
          ports:
            - containerPort: 8089  # Port que l'application écoute dans le container
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8089          # Port interne du service
      targetPort: 8089    # Port que le backend écoute
      nodePort: 30001     # Port exposé par Minikube
  selector:
    app: backend
